### ISSUE TITLE
Mapa mental - Irving Zárate Reyes

### ISSUE THREAD

**Issue by irving1613** [SistemasTecTlaxiaco/mapa-mental-irving1613#2]
[Mapa Mental - Irving Zárate Reyes.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-irving1613/files/7279264/Mapa.Mental.-.Irving.Zarate.Reyes.pdf)

**Comment by 7177981** [comment]
la relación entre conceptos del mapa son claras y también realizo un trabajo llamativo en  cuanto a colores e información es lo suficientemente clara y la relación de esta es de forma un tanto jerárquica- calificación 97 puntos
